# Generated by Django 2.2 on 2019-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_secret',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
