# Generated by Django 2.2.3 on 2019-08-05 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190805_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region_rest',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
