# Generated by Django 2.2.3 on 2019-08-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_post_region_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region_sido',
            field=models.CharField(choices=[('서울특별시', 'Seoul'), ('부산광역시', 'Busan'), ('대구광역시', 'Daegu'), ('인천광역시', 'Incheon'), ('광주광역시', 'Gwangju'), ('대전광역시', 'Daejeon'), ('울산광역시', 'Ulsan'), ('세종특별자치시', 'Sejong'), ('경기도', 'Gyeonggi'), ('강원도', 'Gangwon'), ('충청북도', 'Chungbuk'), ('충청남도', 'Chungnam'), ('전라북도', 'Jeonbuk'), ('전라남도', 'Jeonnam'), ('경상북도', 'Gyeongbuk'), ('경상남도', 'Gyeongnam'), ('제주특별자치도', 'Jeju')], default='==========', max_length=30),
        ),
    ]
