# Generated by Django 2.2.3 on 2019-08-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190809_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region_sido',
            field=models.CharField(choices=[('Seoul', '서울특별시'), ('Busan', '부산광역시'), ('Daegu', '대구광역시'), ('Incheon', '인천광역시'), ('Gwangju', '광주광역시'), ('Daejeon', '대전광역시'), ('Ulsan', '울산광역시'), ('Sejong', '세종특별자치시'), ('Gyeonggi', '경기도'), ('Gangwon', '강원도'), ('Chungbuk', '충청북도'), ('Chungnam', '충청남도'), ('Jeonbuk', '전라북도'), ('Jeonnam', '전라남도'), ('Gyeongbuk', '경상북도'), ('Gyeongnam', '경상남도'), ('Jeju', '제주특별자치도')], default='==========', max_length=30),
        ),
    ]
