# Generated by Django 2.2.3 on 2019-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190809_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice_parcel',
            field=models.CharField(choices=[('가능', '가능'), ('불가능', '불가능')], default='가능', max_length=10),
        ),
    ]
