# Generated by Django 2.2 on 2019-08-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_complaint_servicecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomment',
            name='complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_comments', to='mainapp.Complaint'),
            preserve_default=False,
        ),
    ]
