# Generated by Django 2.2 on 2019-08-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_servicecomment_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceComment',
        ),
    ]
